### ISSUE TITLE
Реализовать возможность выбора через выпадающие списки

### ISSUE THREAD

**Issue by blockin90** [SergeiK99/LAB6#3]
Убрать отдельные кнопки для выбора функции, вместо этого сделать все в одном выпадающем списке
В отдельном выпадающем списке реализовать возможность выбора метода интегрирования.

Выпадающий список - это элемент ComboBox. Свойства, по которым можно узнать, какой элемент выбран:
SelectedIndex - номер выбранного элемента (нумерация с нуля, если значение == -1 , то ничего не выбрано)
SelectedItem - сам выбранный элемент (у тебя скорее всего это строка, но в общем случае м.б. и что-то другое)

если комбобокс, например, называется comboBox1, то:
string value = comboBox1.SelectedItem.ToString(); //строковое значение выбранного элемента
int index = comboBox1.SelectedIndex; //индекс выбранного элемента

**Comment by SergeiK99** [comment]
Сделано
